server:
  port: 8090
spring:
  cloud: 
   gateway:
    routes:
      - id: ruta-productos
          #lb:// cuando se va a acceder a través de Eureka
        uri: lb://servicio-productos #http://localhost:8080
        predicates:
          - Path=/sproductos/**
        filters:
          - RewritePath=/sproductos/*, /
      - id: ruta-pedidos
        uri: lb://servicio-pedidos #http://localhost:8081
        predicates:
          - Path=/spedidos/**
        filters:
          - RewritePath=/spedidos/*, /
eureka:                  
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka  