spring:
  application:
    name: servidor-zuul
server:
  port: 8090
eureka:
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
zuul:
  routes:
    ruta-productos:
      path: /sproductos/**
      service-id: servicio-productos
    ruta-pedidos:
      path: /spedidos/**
      service-id: servicio-pedidos